/* Public surface of `domain/rgbpp`. Everything another module may use is named here;
 * the files behind it are internal. */

export { CKB_FEE, MINER_FEE_RESERVE, minerCellCapacity, occupied, tokenCellCapacity } from "./cells/capacity";
export { TICKET_VOUT, challengeOutpoint, decodeMinerCell, encodeMinerCell } from "./cells/miner";
export type { MinerCell, MinerCellData, MinerStateName } from "./cells/miner";
export type { SealedCell } from "./cells/sealed";
export { decodeAmount, encodeAmount } from "./cells/token";
export type { TokenCell } from "./cells/token";
export { commitment } from "./commitment";
export type { VirtualTx } from "./commitment";
export { ACTIVE_RGBPP, TESTNET } from "./config";
export type { RgbppConfig, ScriptIdentity } from "./config";
export { ckbMintScriptUrl, ckbTokenUrl, ckbTxUrl } from "./explorer";
export { landingMints, positionsOf } from "./holdings";
export type { LandingCandidate, Position } from "./holdings";
export { MAX_PROMOTER_SCRIPT, OWNER_BY_INPUT_TYPE, TERMS_VERSION, decodeTerms, encodeTerms, metadataHash, mintScript, promoterScriptFor, tokenId, tokenScript } from "./launch";
export type { LaunchTerms, TokenMetadata } from "./launch";
export { ARM_ANCHOR_MARGIN, armAnchor, planArm } from "./plans/arm";
export { planMint } from "./plans/mint";
export type { MintRequest } from "./plans/mint";
export { SEAL_SATS, finish } from "./plans/plan";
export type { Paymaster, Plan, PlannedOutput } from "./plans/plan";
export { planTicket } from "./plans/ticket";
export type { TicketRequest } from "./plans/ticket";
export { planTransfer } from "./plans/transfer";
export type { TransferRequest } from "./plans/transfer";
export { BUYER_SEAL_VOUT, checkListing, completePurchase, planPurchase, signListing } from "./sale";
export type { Listing, SignedPurchase } from "./sale";
export { PLACEHOLDER_TXID, isRgbppLock, pendingLock, rgbppLock, sealArgs, sealFromArgs } from "./seal";
export type { Seal } from "./seal";
export { ARM_SHAPE, commitmentScript, fundingNeeded, mintShape, networkFee, plainFunding, shapeOf, signOperation, strippedTx } from "./transaction";
export type { Shape, SignedOperation } from "./transaction";
export { verifyMint } from "./verify";
export type { Check, MintEvidence, MintVerdict } from "./verify";
